name: Harmonic-NAS
channels:
  - defaults
dependencies:
  - pip=23.0
  - python=3.8.10
  - pip:
    - ftfy==6.1.1
    - graphviz==0.20.1
    - h5py==3.9.0
    - librosa==0.7.0
    - numba==0.57.1
    - numpy==1.24.4
    - pandas==2.0.3
    - ipython==8.12.2
    - Pillow==10.0.1
    - pymoo==0.4.0
    - regex==2023.8.8
    - scikit-learn==1.3.0
    - scipy==1.10.1
    - torch==2.0.1
    - torchvision==0.15.2
    - opencv-python==4.8.0.76
    - tqdm==4.66.1
